package customer;

import restaurant.Restaurant;

public class Customer {
    // Constant Attributes
    protected static final int REGULAR_CUSTOMER_CODE_SERIES = 1000;
    protected static final int RENTER_CODE_SERIES = 2000;
    private static final int SPECIAL_CODE_SERIES = 9000;
    protected static final String REGULAR_CUSTOMER = "Regular Customer";
    protected static final String RENTER = "Renter";

    // Static Attributes
    protected static int TOTAL_COUNT = 0;
    protected static int TOTAL_REMOVED = 0;
    protected static int REGULAR_CUSTOMER_TOTAL_COUNT = 0;
    protected static int REGULAR_CUSTOMER_TOTAL_REMOVED = 0;
    protected static int RENTER_TOTAL_COUNT = 0;
    protected static int RENTER_TOTAL_REMOVED = 0;


    // Attributes
    protected final int customerId;
    protected final int customerCode;
    protected String firstName;
    protected String lastName;
    protected Restaurant restaurant;
    protected String customerType;

    /**
     * Creates a new instance of a {@code Customer}.
     *
     * @param firstName the first name of the customer
     * @param lastName  the last name of the customer
     */
    public Customer(String firstName, String lastName, Restaurant restaurant) {
        this.customerId = assignId();
        this.firstName = firstName;
        this.lastName = lastName;
        this.customerCode = assignCode();
        this.restaurant = restaurant;
    }

    /**
     * Decrements the number of existing {@code Customer} instances.
     */
    protected static void decrementTotalCount() {
        TOTAL_REMOVED++;
    }

    // Getters
    public int getCustomerCode() {
        return this.customerCode;
    }

    public String getFirstName() {
        return this.firstName;
    }

    // Setters
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    // Methods

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Assigns an autogenerated ID depending on the currently existing {@code Customer} instances.
     *
     * @return the ID for a customer
     */
    protected int assignId(){
        return ++TOTAL_COUNT;
    }

    /**
     * Assigns an autogenerated code depending on the currently existing {@code Customer} instances.
     *
     * @return the customer code for a customer
     */
    protected int assignCode() {
        return this.customerId + SPECIAL_CODE_SERIES;
    }

    /**
     * Allows a {@code Customer} instance to pay a restaurant, increasing a restaurant's sales.
     *
     * @param amount the amount of money added to the {@code Restaurant} instance's total sales
     */
    protected void pay(float amount) {
        this.restaurant.addToSales(amount);
    }

    /**
     * Prints the basic information of a {@code Customer} to the terminal.
     */
    protected void viewBasicInformation() {
        System.out.println();
        // Determine the type of customer and print it
        if (this.customerType.equals(REGULAR_CUSTOMER)) {
            System.out.println("┄┄┄ Regular Customer ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄");
        } else if (this.customerType.equals(RENTER)) {
            System.out.println("┄┄┄ Renter ┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄");
        }
        System.out.println("Customer ID:    " + this.customerId);
        System.out.println("Customer Code:  " + this.customerCode);
        System.out.println("First Name:     " + this.firstName);
        System.out.println("Last Name:      " + this.lastName);
    }
}
