package customer;

import restaurant.Restaurant;

public class RegularCustomer extends Customer {

    // Attributes
    private int loyaltyPoints;

    // Constructor
    public RegularCustomer(String firstName, String lastName, Restaurant restaurant, int loyaltyPoints) {
        super(firstName, lastName, restaurant);
        this.loyaltyPoints = loyaltyPoints;
        this.customerType = Customer.REGULAR_CUSTOMER;
    }

    // Getters
    public int getLoyaltyPoints() {
        return this.loyaltyPoints;
    }

    // Methods
    /**
     * Decrements the number of existing {@code Customer} instances.
     */
    public static void decrementTotalCount() {
        Customer.decrementTotalCount();
        REGULAR_CUSTOMER_TOTAL_REMOVED++;
    }

    /**
     * Obtains the total number of existing {@code RegularCustomer} instances.
     *
     * @return the total number of existing {@code RegularCustomer} instances
     */
    public static int obtainTotalCount() {
        return REGULAR_CUSTOMER_TOTAL_COUNT - REGULAR_CUSTOMER_TOTAL_REMOVED;
    }

    /**
     * Assigns an autogenerated ID depending on the currently existing {@code RegularCustomer} instances.
     *
     * @return the ID for a regular customer
     */
    @Override
    protected int assignId() {
        ++REGULAR_CUSTOMER_TOTAL_COUNT;
        return ++TOTAL_COUNT;
    }

    /**
     * Assigns an autogenerated code depending on the currently existing {@code RegularCustomer} instances.
     *
     * @return the customer code for a regular customer
     */
    protected int assignCode() {
        return Customer.REGULAR_CUSTOMER_TOTAL_COUNT + Customer.REGULAR_CUSTOMER_CODE_SERIES;
    }

    /**
     * Prints the basic information of a {@code RegularCustomer} to the terminal.
     */
    public void viewState() {
        viewBasicInformation();
        System.out.println("Loyalty Points: " + this.loyaltyPoints);
    }

    /**
     * Allows a {@code RegularCustomer} instance to buy from a restaurant, increasing a restaurant's sales.
     *
     * @param amount the amount of money added to the {@code Restaurant} instance's total sales
     */
    public void buy(float amount) {
        final float conversionRate = 1 / 25f;
        this.loyaltyPoints += (int) Math.floor(amount * conversionRate);
        pay(amount);
        System.out.printf("Success! %s %s has paid %.2f!", this.firstName, this.lastName, amount);
        System.out.println();
    }
}
